# Introduction to NumPy


<div class="alert alert-block alert-info"> <b>Full documentation:</b> https://numpy.org/doc/stable/  </div>

NumPy is the most used library for scientific computing. It is well-optimized and easy-to-use and offers e.g. linear algebra routines and comprehensive mathematical functions.

In [5]:
# imports for this lesson
import time
import numpy as np

## Arrays

An array is a 'grid' of values of the same types. It is indexed by tuples of non negative indices and provides the framework for multiple dimensions. Each array has the following:
- `dtype`, data type. If not expressed, then the data type of the array is the minimum type required to hold the objects in the sequence. 
- `shape`, shape of the data as a tuple. For example, a $3 \times 4$ matrix has shape $(3,4)$.
- `data`, raw data storage in memory.

### Arrays vs lists

In [22]:
length = 100000000
a = list(range(length))
b = [ 0 ] * length

In [33]:
# square of a list
tic = time.time()
for i in range(len(a)):
  b[i] = a[i]**2
toc = time.time()
print(f"Elapsed time: {toc - tic}")

Elapsed time: 5.800724744796753


In [39]:
# np array of the arithmetic sequence of numbers from 0 to length
# with step 1
a_np = np.arange(length)
b_np = np.zeros(length)

In [34]:
# square of an array
tic = time.time()
b_np = a_np ** 2
toc = time.time()
print(f"Elapsed time: {toc - tic}")

Elapsed time: 0.18929457664489746


### Creating arrays

In [38]:
# 1-dimensional array of length 3
a = np.array([1,2,3])
# 2-dimensional array of shape (2,3) -> 3x4 matrix
b = np.array([[1,2,3], [4,5,6]])
print(f"a={a}")
print(f"b={b}")

a=[1 2 3]
b=[[1 2 3]
 [4 5 6]]


In [61]:
# zero array
zero = np.zeros((3,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [62]:
# be careful on data types :)
print(zero.dtype)
zero = np.zeros((3,4), dtype = np.int64)
print(zero.dtype)

float64
int64


In [46]:
# ones array
one = np.ones((2,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
# identity matrix
identity = np.eye(5)
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Basic operations

In [56]:
# compute the shape
print(f"Shape: {one.shape}")
# compute the size, i.e. the number of entries
print(f"Size: {one.size}")
# compute the number of dimensions: e.g. for a vector is 1, for a matrix 2
print(f"Number of dimensions: {one.ndim}")
# compute the data type
print(f"Data type: {one.dtype}")

Shape: (2, 5)
Size: 10
Number of dimensions: 2
Data type: float64


In [68]:
# sum
a = np.array([1,2,3])
b = np.array([4,5,6])
# alternative: np.add
a + b

array([5, 7, 9])

In [69]:
# subtraction
# alternative: np.subtract
a - b

array([-3, -3, -3])

In [70]:
# multiplication (component-wise)
# alternative: np.multiply
a*b

array([ 4, 10, 18])

In [71]:
# division (component-wise)
# alternative: np.divide
a/b

array([0.25, 0.4 , 0.5 ])

In [74]:
# transpose
a = np.array([[1,2,3], [4,5,6]])
print(a)
# more general alternative: np.transpose
a.T

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [75]:
# mean
np.mean(b)

5.0

## Linear Algebra with NumPy

NumPy is perfect for performing linear algebra computations. Some of the most useful routines are the following.
- `@`: matrix-multiplication of two arrays. 
- `np.dot`: compute the dot product of two arrays.
- `np.linalg.norm`: compute the vector or matrix norm.
- `np.linalg.solve`: solve a system of linear equations. 
- `np.linalg.inv`: compute the inverse of a matrix

For a matrix-matrix multiplication it can also be used `np.dot` but `@` is preferred: see [here](https://numpy.org/doc/stable/reference/generated/numpy.dot.html#numpy.dot).

In [81]:
# matrix-vector product
M = np.ones((3,2), dtype = np.int64)
a = np.ones(2, dtype = np.int64)
M @ a

array([2, 2, 2])

In [86]:
# matrix-matrix product
M @ M.T

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [89]:
# dot product
# alternative for vectors: np.vdot()
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

In [92]:
# norm
np.linalg.norm(a)

3.7416573867739413

In [97]:
# linear-system solve
A = np.array([[1,2], [0, 1]])
b = np.array([3,4])
x = np.linalg.solve(A,b)
print(f"The solution of the system Ax = b is: {x}")

The solution of the system Ax = b is: [-5.  4.]


In [98]:
# solution check
A @ x

array([3., 4.])

In [100]:
# inverse of a matrix
A = np.array([[1,2], [0, 1]])
A_inv = np.linalg.inv(A)
A_inv

array([[ 1., -2.],
       [ 0.,  1.]])

In [101]:
# inverse check
A @ A_inv

array([[1., 0.],
       [0., 1.]])